### PR TITLE
Fix outdated `deployEnvironmentTriggers` mutation

### LINKED ISSUE #266: Redeployment with new variables from `railway variables set` fails with status code 400
At the moment updating variables with `railway variables set` is not working correctly. The variables get updated correctly, but the triggered redeploy fails with status code 400. My guess is the endpoint was slightly changed broken that part of the command. This problem has been reproduced by another member on the Discord server which indicates it's most likely wrong on your end.

image

### PR DESCRIPTION
**Pull request by ChristianIvicevic**
This draft attempts to fix an outdated mutation to trigger a redeploy. I attempted to reuse the inferred `serviceID` and return it to the original callsite causing some changes here and there.

Unfortunately during local testing the mutation was successfully invoked but no redeployment was initiated server-side. I guess this is just filtered based on the headers disallowing CLI redeployments which may be intended for now or just a bug. The very same mutation fired from the UI by updating any variable does work though. As such this probably requires somebody to check that on your end.

Another observation I made is the type of mutation parameters. The server returns a 400 status code when the types are declared as `String!` instead of `ID!`. This is highly inconsistent with other queries and mutations expecting `String!` instead. My assumption is that this is a very old endpoint you exposed and haven't updated it yet.

I'll keep this a draft until the open questions are resolved and the correctness of the implementation has been confirmed.

Closes #266

### CODE REVIEW

**Comment by ChristianIvicevic** [comment]
After some discussion on Discord the endpoint was fixed and I could confirm that the CLI command now works. I was also able to deduce the correct link for the new deployment log.

File: cmd/variables.go [hunk 1]
```diff
@@ -72,7 +78,7 @@ func (h *Handler) VariablesSet(ctx context.Context, req *entity.CommandRequest)
 		updatedEnvNames = append(updatedEnvNames, key)
 	}
 
-	err = h.ctrl.UpsertEnvs(ctx, variables, &serviceName)
+	serviceID, err := h.ctrl.UpsertEnvs(ctx, variables, &serviceName)
```
Comment (JakeCooper) [inline cmd/variables.go:81]: Would rather have an extra call to get the serviceId from serviceName than to change the function signature here

File: cmd/variables.go [hunk 2]
```diff
@@ -57,6 +57,12 @@ func (h *Handler) VariablesSet(ctx context.Context, req *entity.CommandRequest)
 		return err
 	}
 
+	noRedeploy, err := req.Cmd.Flags().GetBool("no-redeploy")
```
Comment (JakeCooper) [inline cmd/variables.go:60]: Just copy nit here
```suggestion
	noRedeploy, err := req.Cmd.Flags().GetBool("skip-redeploy")
```

File: cmd/variables.go [hunk 3]
```diff
@@ -86,7 +92,7 @@ func (h *Handler) VariablesSet(ctx context.Context, req *entity.CommandRequest)
 	fmt.Print(ui.Heading(fmt.Sprintf("Updated %s for \"%s\"", strings.Join(updatedEnvNames, ", "), environment.Name)))
 	fmt.Print(ui.KeyValues(*variables))
 
-	err = h.redeployAfterVariablesChange(ctx, environment)
+	err = h.redeployAfterVariablesChange(ctx, environment, serviceID, noRedeploy)
 	if err != nil {
```
Comment (JakeCooper) [inline cmd/variables.go:96]: Ideally the redeployAfterVariablesChange shouldn't be aware of the flag. Should just have an `if !noRedeploys` at the top level here and keep the function signature clean

File: cmd/variables.go (hunk 1 above)
Comment (ChristianIvicevic) [reply cmd/variables.go:81]: I have been thinking about something similar but went naively with that approach since `UpsertEnvs` does a lot of steps to obtain the serviceID which is why I wanted to reuse the value it just computed. Can you elaborate what alternative you had in mind?

Comment (JakeCooper) [reply cmd/variables.go:81]: Hoist the work required to get serviceId from name into another function, call that function above, then pass in the serviceId if you want

Comment (ChristianIvicevic) [reply cmd/variables.go:81]: I see. The same snippet to obtain the serviceID by name was actually copy & pasted multiple times across the codebase already. I'll have a look at it, but can't promise anything since it's also used in unrelated parts of the codebase.

Comment (JakeCooper) [reply cmd/variables.go:81]: Oh you don't have to refactor all of it. I'd just refactor it inline here and then we can move to pulling the usage into one function at some point

Comment (ChristianIvicevic) [reply cmd/variables.go]: Alright, I came with something, but wasn't fully sure where to put it exactly to not copy & paste even more. Hope that this is better.

**Review by JakeCooper — APPROVED** [review]
Awesome!

File: cmd/variables.go (hunk 1 above)
Comment (JakeCooper) [reply cmd/variables.go]: Looks perfect great job!
