### PR TITLE
fix<run>: allows `railway run` to run batch scripts on windows, including pnpm and npm.

### LINKED ISSUE #386: `railway run` can't run batch files
2023-03-16 20_52_47-dayjs

this is more so of an issue since `npx` is a cmd file on windows, thus you can't do `railway run npx ...`

the workaround is `railway shell` and then run the `npx` commands (or batch files)

### PR DESCRIPTION
**Pull request by alexng353**
Fixes #386
Allows `railway run` to run other batch script windows programs, such as pnpm and npm.

- one match statement that sets the child proc and does all the argument handling
- moved command spawning away from the match statemnt
- handles no argument passed

### CODE REVIEW

**Comment by brody192** [comment]
i like

File: src/commands/run.rs [hunk 1]
```diff
@@ -144,13 +144,30 @@ pub async fn command(args: Args, _json: bool) -> Result<()> {
...
     })?;
 
-    let exit_status =
-        tokio::process::Command::new(args.args.first().context("No command provided")?)
-            .args(args.args[1..].iter())
-            .envs(variables)
-            .status()
-            .await
-            .context("Failed to spawn command")?;
+    let slash_c = "/C".to_owned();
```
Comment (aleksrutins) [inline src/commands/run.rs:147]: There _has_ to be a better way to do this...

Down below, you could probably replace `&slash_c` with `"/C".into()`, right?

**Review by aleksrutins — APPROVED** [review]
LGTM, just a bit of feedback.

File: src/commands/run.rs (hunk 1 above)
Comment (alexng353) [reply src/commands/run.rs:147]: I'll make the change during lunch break, I'm not so familiar with rust stuff yet. Thanks for the comment!

Comment (alexng353) [reply src/commands/run.rs]: Can't borrow the "/C".into() value since it is dropped too quickly. Instead, I just mapped args.args into a Vec<&str>.

File: src/commands/run.rs [hunk 2]
```diff
@@ -144,13 +144,30 @@ pub async fn command(args: Args, _json: bool) -> Result<()> {
...
+    let mut args = args.args.iter().collect::<Vec<_>>();
+    if args.is_empty() {
+        bail!("No command provided");
+    }
+
+    let child_process_name: &str;
```
[the remark this answers is not in the document]
Comment (alexng353) [reply src/commands/run.rs]: I just made the inter happy instead.

File: src/commands/run.rs [hunk 3]
```diff
@@ -144,13 +144,28 @@ pub async fn command(args: Args, _json: bool) -> Result<()> {
...
-            .envs(variables)
-            .status()
-            .await
-            .context("Failed to spawn command")?;
+    let mut args = args.args.iter().map(|s| s.as_str()).collect::<Vec<_>>();
+    if args.is_empty() {
+        bail!("No command provided");
+    }
+
+    // So the linter doesn't get mad. I think this is pretty ugly.
```
Comment (coffee-cup) [inline src/commands/run.rs:152]:
```suggestion
```

File: src/commands/run.rs [hunk 4]
```diff
@@ -144,13 +144,28 @@ pub async fn command(args: Args, _json: bool) -> Result<()> {
...
+    let child_process_name = match std::env::consts::OS {
+        "windows" => {
+            args.insert(0, "/C");
+            "cmd"
+        }
+        _ => {
+            args.remove(0);
```
Comment (coffee-cup) [inline src/commands/run.rs:159]: This doesn't seem to work

image

File: src/commands/run.rs [hunk 5]
```diff
@@ -144,13 +144,28 @@ pub async fn command(args: Args, _json: bool) -> Result<()> {
...
+            args.first().context("No command provided")?
```
Comment (coffee-cup) [inline src/commands/run.rs:160]: We are removing the first arg from the args array but then want to return it from the match. This can be changed to just remove the first item and return it

```suggestion
            args.remove(0)
```

File: src/commands/run.rs (hunk 3 above)
Comment (coffee-cup) [reply src/commands/run.rs:152]: If you want to remove the match, you could change to an if

```rust
let child_process_name = if std::env::consts::OS == "windows" {
  args.insert(0, "/C");
  "cmd"
} else {
  args.remove(0)
}
```

**Comment by alexng353** [comment]
In the middle of checking some compatibility issues on non-windows brought up by @brody192

**Comment by alexng353** [comment]
> In the middle of checking some compatibility issues on non-windows brought up by @brody192

I think that the issue I was chasing was fixed by @coffee-cup 's suggestion here. Couldn't replicate the bug on my mac or linux machine, so I think its good.
image

**Review by coffee-cup — APPROVED** [review]
